### ISSUE TITLE
Feature request for useAudio or useSound

### ISSUE THREAD

**Issue by glinda93** [antonioru/beautiful-react-hooks#198]
**Is your feature request related to a problem? Please describe.**
React custom hook for playing audios

**Describe the solution you'd like**
Something like this one: [StackOverflow: Playing sound in React.js](https://stackoverflow.com/q/47686345/11792577)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by antonioru** [comment]
Hi @glinda93 

thank you very much for opening this issue, at the moment there's no plan to create audio-related hooks, but feel free to pen a pull request

**Comment by Ashwin-Codes** [comment]
Hi @antonioru, I will love to work on this custom audio hook. I think it will be a great addition to 'beautiful-react-hooks'. Shall I work on it ?

**Comment by antonioru** [comment]
> Hi @antonioru, I will love to work on this custom audio hook. I think it will be a great addition to 'beautiful-react-hooks'. Shall I work on it ?

Hi @Ashwin-Codes 
yes, that would be very much appreciated :)
Thanks!

**Comment by playerony** [comment]
I started working on that today, so should be ready in days :)

**Comment by antonioru** [comment]
Closed by #383
