### ISSUE TITLE
Unable to preventDefault inside passive event listener due to target being treated as passive.

### ISSUE THREAD

**Issue by yoshino** [antonioru/beautiful-react-hooks#258]
**Describe the bug**
When using `useSwipe` or `useSwipeEvents`, the console of Chrome DevTools shows error logs like below.

```
bundle.9dceb1d3.js:2 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
```

I confirmed that passing the `passvie: false` options to `addEventListener` solves this plobrem.

```js
target.addEventListener(eventName, cb, { passive: false })
```

↑ code is  [here](https://github.com/beautifulinteractions/beautiful-react-hooks/blob/master/src/utils/assignEventCallbackOnMountEffect.js#L21)

**To Reproduce**
1. Go to [useSwipe Live demo](https://beautifulinteractions.github.io/beautiful-react-hooks/#/useSwipe)
2. Fire swipe events in global example or options example
3. Open Chrome DevTools

**Expected behavior**
These hooks can set preventDefault value as option and , the console of Chrome DevTools shows no error.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: chrome
 - Version:  91.0.4472.77

**Comment by antonioru** [comment]
HI @yoshino thank you very much for opening this issue! 
I'll do my best to address it as soon as possible, in the meanwhile feel free to open a pull request 

cheers

**Comment by antonioru** [comment]
closed by @playerony PRs
