### ISSUE TITLE
useLocalStorage does not sync between multiple instances

### ISSUE THREAD

**Issue by PupoSDC** [antonioru/beautiful-react-hooks#307]
**Describe the bug**

Two instances of the `useLocalStorage` are not synced between each other

**To Reproduce**

Check the following js fiddle that boils down the problem as much as possible: https://codesandbox.io/s/react-boilerplate-forked-s4hz2

**Expected behavior**

All instances of the hook force a rerender when the underlying value changes

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Browser chrome
 - Version 94.0.4606.71

**Suggestion**

This can be easily implemented by adding a listener to [Window storage event](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event)

**Comment by antonioru** [comment]
Hello @PupoSDC 
thanks for reporting this issue. 
I think the documentation of `useLocalStorage` might a bit misleading and needs to be expanded but... the hook is actually supposed to work exactly as you described. 
`useLocalStorage` is only meant to wrap the business logic of setting/getting a value from the local storage, it doesn't expose a state therefore setting the value of a local storage key doesn't cause any re-render of the component(s). 
It's the same in plain javascript: when you change the value of a local storage key... you only change that value, nothing really happens and assuming the local storage represents a state it's actually an opinionated vision of the local storage. 

You can use `useGlobalEvent` to attach a listener to the 'storage' item and wrap your own hook on top of that.

**Comment by PupoSDC** [comment]
On the one hand I agree that the documentation can be improved... on the other, I'm not sure I agree that is the best possible implementation of the hook. 

In my opinion, a hook for a value for setting or reading from an arbitrary source of memory, should just be a portal to that value, and be a truthful representation of the most up to date value stored there. The current implementation, as you described, reflects better a `getter` and `setter` paradigm, which in this case is a bit tricky, since we don't really have a `getter`, but a provided value we have no explicit way of refreshing.

For my project, I ended up implementing what I needed based on your source code:

```ts
const storage = window.localStorage;

const readStorageValue = <T>(key: string, defaultValue?: T): T => {
  try {
    return JSON.parse(storage.getItem(key) as string);
  } catch (e) {
    return defaultValue as T;
  }
};

export const useLocalStorage = <T>(
  key: string,
  defaultValue?: T
): [T, Dispatch<SetStateAction<T>>] => {
  const [value, setValue] = useState(readStorageValue(key, defaultValue));

  useEffect(() => {
    storage.setItem(key, JSON.stringify(value));
    window.dispatchEvent(new Event("localStorageUpdate"));
  }, [key, value]);

  useEffect(() => {
    const onStorageUpdateValue = () => setValue(readStorageValue(key, value));
    window.addEventListener("storage", onStorageUpdateValue);
    window.addEventListener("localStorageUpdate", onStorageUpdateValue);
    return () => {
      window.removeEventListener("storage", onStorageUpdateValue);
      window.removeEventListener("localStorageUpdate", onStorageUpdateValue);
    };
  }, [key, value]);

  return [value, setValue];
};
```

It's a bit clunky, but for now it satisfies the needs of my app. 

In any case, thanks a lot for coming back to me so fast. If you are interested in changing a bit how this hook works, I'm glad to help, otherwise, feel free to close the issue! :smiley:
