### ISSUE TITLE
set up Travis CI for this repository

### ISSUE THREAD

**Issue by antonioru** [antonioru/beautiful-react-hooks#31]
Setup Travis CI for this repository:

- Clear the local modules
- Install everything again
- running the tests
- build the library
- If the destination branch is master, pubish the content of the `dist-ghpages` directory to the branch `ghpages`
- if the destination branch is master, publish the new version of the library to npm

**Comment by theashraf** [comment]
I'd like to help with this one.
What scripts or pipelines that you want Travis to run?

**Comment by antonioru** [comment]
Hello @theashraf, 
thank you for answering and yes I would love to have your help on this task.

I've already started something in the `feature/travis-ci` branch and just pushed it, feel free to start from there. 
I am not really a **Travis CI** expert and I was quite experimenting with it, so if you have to change the `.travis.yml` file completely, just do it.

What I would like to have is: 

- Clear the local modules
- Install everything again
- running the tests
- build the library
- If the destination branch is master, pubish the content of the `dist-ghpages`directory to the branch `ghpages`
- if the destination branch is master, publish the new version of the library to npm

As mentioned I'm not really an expert so I'm open to suggestions 

thank you, 

A.
