### ISSUE TITLE
Use dark mode

### ISSUE THREAD

**Issue by lukasoppermann** [antonioru/beautiful-react-hooks#317]
**Is your feature request related to a problem? Please describe.**
Missing a hook that allows easy dark mode usage.

I have been using https://github.com/donavon/use-dark-mode but it seems to me unsupported. It would be great if you could add a hook here.

**Describe the solution you'd like**
It should allow to toggle darkmode.
It should also allow to enable a feature that automatically reads out the prefer-color-scheme media query.

**Comment by antonioru** [comment]
Hi @lukasoppermann 
thanks for opening the issue 
Yes, `useDarkMode` would be a good hook to have in the library. 
Please feel free to contribute and add it yourself
Looking forward to your contribution

**Comment by lukasoppermann** [comment]
Hey @antonioru 

I am not the most advanced react developer. I could try to port the other package and maybe simplify it a bit.
If you can have a look and potentially advice, I would be happy to try.

**Comment by antonioru** [comment]
@lukasoppermann that's exactly what open source is about: I'd love to give you any advice needed :)
