### ISSUE TITLE
The second parameter 'distinct' of useValueHistory does not make sense

### ISSUE THREAD

**Issue by wiskewu** [antonioru/beautiful-react-hooks#322]
**Describe the bug**
When passing `true` to second parameter, the historyValues does not filter duplicated values;

**To Reproduce**
An simple example goes below:
```javascript
let ticks = 0;

function Example() {
  const [count, setCount] = useState(0);
  const historyValues = useValueHistory(count, true);

  useInterval(() => {
    setCount(++ticks % 2);
  }, 1000);

  return (
    <div>
       OLD VALUES: {historyValues.join(',')}
    </div>
  )
}
```
**Expected behavior**
historyValues variable expected to be `[0, 1]` instead of `[0, 1, 0, 1, 0, 1, 0...]`;

**Additional context**
This occurred because of misuse of `filter` function under the hood:
```javascript
// sourcecode of useValueHistory hook:

const useValueHistory = (value, distinct = false) => {
  const history = useRef([]);
  
  useEffect(() => {
    history.current.push(value);
    if (distinct) {
      // unexpected use of filter:
      history.current.filter(distinctValues); 
      // may intended to be like this:
      // history.current = history.current.filter(distinctValues);
    }
  }, [value])


  return history.current;
}
```

**Comment by antonioru** [comment]
Hi @wiskewu thanks for opening this issue, I think you're right and you spotted the bug!
it is a misuse of the Array.prototype.filter function! 

Please feel free to open a pull request to quickly fix it
