### ISSUE TITLE
useResizeObserver reports incorrect return type

### ISSUE THREAD

**Issue by genepaul** [antonioru/beautiful-react-hooks#325]
**Describe the bug**
`useResizeObserver` reports that it returns `DOMRectValues`. However, the state variable `DOMRect` is initialized to `undefined`, which will cause the first render with that hook to return `undefined`. Indeed, the documentation seems to demonstrate that you should always check for the existence of the DOMRect before doing anything with it. I can definitely open a PR to fix this.

**To Reproduce**
1. Use the results of `useResizeObserver` in a TypeScript environment, and realize that it is potentially undefined.

**Expected behavior**
I would like it to report `DOMRectValues | undefined`.

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version latest

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version latest

**Additional context**

**Comment by antonioru** [comment]
Hey @genepaul thanks for pointing this out and thanks for your PR, I'll review it soon
