### ISSUE TITLE
useResizeObserver TypeScript issues

### ISSUE THREAD

**Issue by genepaul** [antonioru/beautiful-react-hooks#327]
**Describe the bug**
This isn't exactly a bug, but more a nuance of how useResizeObserver reports its types and the effects for TypeScript users.

`useResizeObserver` reports that it accepts a `MutableRefObject<T>`, where `T extends HTMLElement`. In your documentation for the hook, you demonstrate that user can pass a ref that is declared: `const ref = useRef()`. If a TypeScript user tries to use that code as-is, they will get the following error:

```
Argument of type 'MutableRefObject<undefined>' is not assignable to parameter of type 'MutableRefObject<HTMLElement>'.
  Type 'undefined' is not assignable to type 'HTMLElement'.ts(2345)
```

And if they try to update it to `const ref = useRef<HTMLElement>()`, they'll get the following error:

```
Argument of type 'MutableRefObject<HTMLElement | undefined>' is not assignable to parameter of type 'MutableRefObject<HTMLElement>'.
  Type 'HTMLElement | undefined' is not assignable to type 'HTMLElement'.
    Type 'undefined' is not assignable to type 'HTMLElement'.ts(2345)
```

What's happening here is a nuance of how React considers *mutable* vs. *immutable* refs: https://dev.to/wojciechmatuszewski/mutable-and-immutable-useref-semantics-with-react-typescript-30c9. I think what you want is an `immutable` ref, because as the linked article describes, we're trying to use a ref that will be managed by React (we're just passing it as a ref to a DOM element, not assigning to it or initializing it ourselves). So I think the type should be updated to `RefObject<HTMLElement>`.

In fact, with the current typing, there's an eslint rule that tells you not to use unnecessary conditionals when a value has been typed as always truthy. When you define something as a `MutableRefObject<T>`, you are telling TypeScript that the value in `current` will always be defined as T. However, `RefObject<T>` assumes that `current` could be null, because that's what is expected when you want to manage a dom ref - it starts out null, then React assigns it the value of the dom element on first render:

![image](https://user-images.githubusercontent.com/66479/151567044-8e919277-2a4b-426d-a0d6-2a7ff2027694.png)

While we're on the topic of ref types, the typing for `observerRef` is also incorrect. It is typed as a `RefObject<ResizeObserver>`, which is *immutable*, but then you assign to `current`, which means it should be *mutable*.  If you update the declaration to: `const observerRef = useRef<ResizeObserver | null>(null)`, it makes it a MutableRefObject. That of course requires you to deal with the fact that `current` could be null in later code, but it's nice that modern browsers support the optional chaining operator (though you might still need to babelify it due to [Webpack 4 not supporting it](https://github.com/webpack/webpack/issues/10227)).

I'll put up a PR making the changes I think need to be made and 

**To Reproduce**
1. Use useResizeObserver in a TypeScript project

**Expected behavior**
See above for description

**Comment by antonioru** [comment]
hi @genepaul 
yes, I think you're absolutely right! 
To give you a bit of context: this library was originally written in plain javascript and then ported to typescript overnight by community request (a language I'm not a big fan of, TBH). 
Meaning I do expect quite a lot of this nuance in the code. 

That said, your PR would actually be a blessing :) 
Do you think you can possibly fix this everywhere I've used MutableRefObject?
I'm quite sure this issue doesn't affect useResizeObserver only 

Thanks for your interest in improving the project :)
