### ISSUE TITLE
useMutationObserver hook

### ISSUE THREAD

**Issue by genepaul** [antonioru/beautiful-react-hooks#329]
**Is your feature request related to a problem? Please describe.**
I'm currently using this library for a couple other hooks, and it would be great if I could just use this library for all my needs, but in order to do so, there needs to be a MutationObserver hook. It's strange, but it seems that all the hooks libraries out there seem to either have a `ResizeObserver` hook or a `MutationObserver` hook, but not both. It'd be great if I could use one library for both purposes.

**Describe the solution you'd like**
It could be very simple: provide a ref and a callback that should get called whenever mutation occurs. Might also need an options object to provide options to the MutationObserver:

```
function useMutationObserver<T extends HTMLElement>(ref: RefObject<T>, callback: (mutationList: MutationRecord[], observer: MutationObserver) => void, config?: MutationObserverInit): void
```

**Describe alternatives you've considered**
Currently using `@rooks/use-mutation-observer`

**Comment by antonioru** [comment]
hi @genepaul 
thanks for this request! 
Yes `useMutationObserver ` would be a great addition to the library and to be honest I should have something like that in one of my projects but never really had the time to bring it into the library. 
Are you planning to open a PR on this?

**Comment by antonioru** [comment]
@genepaul @playerony I'm closing this since this hook has been introduced by @playerony !

Well done mate!
