### ISSUE TITLE
useCookie

### ISSUE THREAD

**Issue by 0529bill** [antonioru/beautiful-react-hooks#330]
**Is your feature request related to a problem? Please describe.**
missing a hook that allows user to access, update and delete cookies 

**Describe the solution you'd like**
the hook should allow user to access, update and delete current cookies value

**Comment by antonioru** [comment]
hi @0529bill thanks for the suggestions, yeah I think that would be a great hook for the library. 
Feel free to open a PR if you want to

**Comment by 0529bill** [comment]
hi, @antonioru do you mind taking a look at the changes I made regarding the new useCookie feature and giving me some advice and feedback!  Thanks in advance. !!
[useCookie](https://github.com/0529bill/beautiful-react-hooks/commit/bf8986d1f9236435b28712cbef5b81b524588d5a)

**Comment by antonioru** [comment]
@0529bill wow that's amazing! 
Please open a PR!!! :) <3

**Comment by antonioru** [comment]
@0529bill do you think you can open a PR with your contribution?
I recently came across a use case where a `useCookie` hook would've solved my problem... I think we'll need to have it in the library soon :)

**Comment by 0529bill** [comment]
@antonioru yes! I would love to!

**Comment by antonioru** [comment]
thanks @0529bill well then I'll wait for your PR, please let me know if you need any help

**Comment by playerony** [comment]
Oh sorry, but I've been working on that since yesterday and I didn't notice someone going to work on it also :( There was not much activity on this issue so I decided to move on

**Comment by 0529bill** [comment]
@playerony actually i've been kinda busy lately.. so feel free to keep on working on this feature and  make a pull request!

**Comment by antonioru** [comment]
ok then I'll check @playerony 's PR soon :) 
thanks guys

**Comment by antonioru** [comment]
guys I'm closing this since it has been introduced by useCookie by @playerony 

@0529bill your feedback is very welcome
