### ISSUE TITLE
Your latest release was a breaking change, not a minor

### ISSUE THREAD

**Issue by njbmartin** [antonioru/beautiful-react-hooks#333]
Not sure if this was an accident, but you introduced a breaking change by renaming hooks.

Might be a good idea to introduce a quick patch to alias the old hooks. eg.

```ts
export { default as useDebouncedCallback, default as useDebouncedFn } from './useDebouncedCallback'
export { default as useThrottledCallback, default as useThrottledFn } from './useThrottledCallback'
```

**Comment by antonioru** [comment]
@njbmartin thanks for pointing this out! 
I think a quick patch would be the right thing to do, I'll do it as soon as possible or if you feel like it, feel free to open a PR

**Comment by genepaul** [comment]
Actually, the function signatures themselves changed as well. I would recommend reverting the commit that rewrote these, releasing that as 1.2.1, then reapplying the commit and re-relasing that as 2.0.0.
