### ISSUE TITLE
useResizeObserver doesn't work with changing refs

### ISSUE THREAD

**Issue by sandrosc** [antonioru/beautiful-react-hooks#342]
Changing refs, like in the following example, leads to both DOM nodes being observed, since the first node is never unobserved.
```ts
const DOMRect = useResizeObserver(first ? ref1 : ref2);
```

Example: https://codesandbox.io/s/black-dew-36k642?file=/src/App.js
1. First box is being observed, second box not.
2. Click button.
3. Expected: Second box should be observed, first box not. Actual behaviour: Both boxes are observed.

**Comment by antonioru** [comment]
@sandrosc you should use two different useResizeObserver for ref1 and ref2
