### ISSUE TITLE
Should export onError for useGeolocationState

### ISSUE THREAD

**Issue by MinChanSike** [antonioru/beautiful-react-hooks#360]
If can get `onError ` event on `useGeolocationState`, more helpfull.
 
Sometime, just request geo position for one time and handle the error.

Does not want to watch position like `useGeolocation` and `useGeolocationEvents`.

Thanks.

**Comment by antonioru** [comment]
Hi @MinChanSike sorry for the late reply.
thanks for the suggestion please feel free to open a PR

**Comment by antonioru** [comment]
I'm closing this since has been fixed by @playerony #369
