### ISSUE TITLE
remove index.ts from the codebase to force correct imports

### ISSUE THREAD

**Issue by antonioru** [antonioru/beautiful-react-hooks#378]
### Discussed in https://github.com/antonioru/beautiful-react-hooks/discussions/377

<div type='discussions-op-text'>

<sup>Originally posted by **antonioru** June 28, 2022</sup>
The correct way to import hooks from this library is:

```ts
import useSomething from 'beautfiul-react-hooks/useSomething';
```

but I've noticed quite often people just go with the ES6 named imports like (probably because it's suggested by the IDE):

```ts
import { useSomething } from 'beautiful-react-hooks';
```

this will import the whole library, which might result in increasing the bundle size. 
To solve this I would like to remove the `index.ts` file from the library and "force" the developers to use the default imports. 

This will obviously be a breaking change so I'd like to have some opinions here :)</div>

**Comment by playerony** [comment]
The package does not support tree shaking, that we should make such a drastic change? At the end of the day, bundled javascript by any and maintained bundler should three shake dead code.

**Comment by antonioru** [comment]
> The package does not support tree shaking, that we should make such a drastic change? At the end of the day, bundled javascript by any and maintained bundler should three shake dead code.

I understand your point and yes, I think you're correct 99% of the times since using this library implies using React which probably means they're using webpack or rollup or vite or anything of that sort... 

on the other hand, three-sharking is not an automatic feature that should be configured and therefore can be mis-configured by the user. 

I wonder if it's our duty to "force" the user to write "good code" by imposing default exports...
I don't have an answer to be honest :))

**Comment by playerony** [comment]
So I think if it's a 99% of the user's bundlers coverage + to be honest it's a breaking change and I'm not sure if necessary and worth change.

**Comment by antonioru** [comment]
> So I think if it's a 99% of the user's bundlers coverage + to be honest it's a breaking change and I'm not sure if necessary and worth change.

fair enough... I'll do some research so I can possibly propose the right solution. 
I'm closing this issue for now then
