### ISSUE TITLE
useAudio hook can't change src when input new src

### ISSUE THREAD

**Issue by bs32g1038** [antonioru/beautiful-react-hooks#393]
https://github.com/antonioru/beautiful-react-hooks/blob/ae46e0988e6d85d57088d09e8ec9ca7d90a7fe5d/src/useAudio.ts#L110
**demo:**
```js
const UseAudioComponent = () => {
  const [src, setSrc] = useState("");
  const [state, controls] = useAudio(src, { autoPlay: true });
  useEffect(() => {
    setSrc("https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3");
  }, []);
};
```
**expect:**
After change src source, audio can play normally.

**Comment by antonioru** [comment]
hi @bs32g1038 thanks for opening this issue, I'm not sure the useAudio hook is supposed to work that way to be honest... if you want it to be reactive please feel free to submit a PR

**Comment by antonioru** [comment]
The way I see this is that it should be done this way:

```
const UseAudioComponent = () => {
  const [state1, controls1] = useAudio(src1, { autoPlay: true });
  const [state2, controls2] = useAudio(src2, { autoPlay: false });
  
  useEffect(() => {
    controls1.play()
  }, []);
};
```

I'm closing this for now
