### ISSUE TITLE
useLocalStorage causing infinite loops when setValue is a dependency in a useEffect

### ISSUE THREAD

**Issue by jaalru** [antonioru/beautiful-react-hooks#395]
**Describe the bug**
`createStorageHook` used by `useLocalStorage` is returning a new `setValue` function every time a new value is stored via `setValue`. This is resulting in infinite loops when `setValue` is being used as a dependency in an `useEffect`.

**To Reproduce**
1. create a component using `useLocalStorage`
2. create an `useEffect` where you update the value of local storage to be a random string.

**Expected behavior**
`setValue` shouldn't have a new ref **unless** the `storageKey` changes.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
The following `SetValue` code may be useful.
```
    const setValue: SetValue<TValue> = useCallback(
      (value: TValue) => {
        setStoredValue((current: TValue) => {
          const valueToStore = value instanceof Function ? value(current) : value
          safelySetStorage(JSON.stringify(valueToStore))
          return valueToStore
        })
      },
      [safelySetStorage]
    )
```

**Comment by antonioru** [comment]
hi @jaalru thanks for reporting this issue and for the detailed report. 
Please feel free to open a PR to fix it

**Comment by antonioru** [comment]
Well done @jaalru PR is in review ;)
