### ISSUE TITLE
More feature from thrid libs

### ISSUE THREAD

**Issue by PatrykKuniczak** [antonioru/beautiful-react-hooks#399]
**Is your feature request related to a problem? Please describe.**
I have a question/suggestion for create your lib, as a complete hooks packages, because i will watching for hooks, and ur repository is only active, and relase latest version 2 weeks ago.
U could be like little framework with all aviables hooks :)

**Describe the solution you'd like**
My solution is implement some hooks ep. useAuth, useRequireAuth, useEventListener from this 2 libs:
https://github.com/juliencrn/usehooks-ts
https://github.com/uidotdev/usehooks

Not all of that is TS friendly, you must type it before relase :)

Maybe i will help, but i'm very busy right now, and i must learn how to make test's in React :)

Cheers

**Comment by antonioru** [comment]
hi, @PatrykKuniczak thanks for your suggestion and for using the library! 

I believe this library should maintain a framework-agnostic and unopinionated stance. 
This means that hooks related to any specific libraries (like oAuth) or any particular business logic (like a possible useAuth), should not be included in the library and instead be reserved for app-specific domains.

However, please bear in mind that this is just my personal viewpoint as the library has evolved into a collaborative effort, with hooks built on top of react-router (for example) and a typescript rewrite, I invite you to contribute your thoughts on the matter. 
So feel free to open a PR and make your voice heard :)

**Comment by antonioru** [comment]
That being said, I'll close it now. 
Keep up the good work
