### ISSUE TITLE
Type declaration error with useInterval hook's clearInterval function

### ISSUE THREAD

**Issue by SirZach** [antonioru/beautiful-react-hooks#402]
**Describe the bug**
`useInterval` is typed as
```
declare const useInterval: <TCallback extends GenericFunction>(fn: TCallback, milliseconds: number, options?: UseIntervalOptions) => (boolean | (() => void))[];
```
which means when you do
```
const [isCleared, clearInterval] = useInterval(() => { }, 1000)
```
`clearInterval` cannot be called as a function since TS thinks it's either a boolean or a function.

**To Reproduce**
Just follow the description with version `3.12.2`

**Expected behavior**
`useInterval` should return `[boolean, () => void]` as the type

**Screenshots**
![Screenshot 2023-03-10 at 11 22 43 AM](https://user-images.githubusercontent.com/1113484/224368800-d01973fa-7f1c-48c5-9813-f7e35fc1ee84.png)

**Comment by antonioru** [comment]
Hey Zach, thanks for taking the time to report this and for being a user of the library 😊

You're totally right, that issue you spotted is incorrect and it definitely needs to be fixed.
I've got a re-factoring of the TypeScript types and some better documentation in the works. 
Unfortunately, I can't give you an exact release date just yet... but it's on its way!

In the meantime, if you feel up to it, open a pull request
Should be a quick and easy fix and you'll get some good karma points 😊

Thanks again for your support

**Comment by shyamtawli** [comment]
I can try my hands on it. If you like to please assign me.

**Comment by shyamtawli** [comment]
Hey can try to fix it?

**Comment by antonioru** [comment]
> Hey can try to fix it?

you're more than welcome

**Comment by shyamtawli** [comment]
Hey @SirZach I have found the file, can you guide me into solving ?

**Comment by antonioru** [comment]
@shyamtawli 
you just need to type the result of the `useInterval` hook.

Something like:
```
return [isCleared, clear] as [boolean, () => void]
```

the same problem is probably affecting `useTimeout` as well

**Comment by shyamtawli** [comment]
Thanks @antonioru for helping me. I have completed what you mentioned above for both useInterval and useTimeout.
That's it ? Should I open a PR.

**Comment by antonioru** [comment]
yes, just run the tests and build the app to make sure everything works. 
If so, feel free to open the PR

**Comment by antonioru** [comment]
@shyamtawli well done!

**Comment by shyamtawli** [comment]
Thanks for helping me @antonioru
