### ISSUE TITLE
:memo useWillUnmount should called useUnmount

### ISSUE THREAD

**Issue by little-buddy** [antonioru/beautiful-react-hooks#414]
https://github.com/antonioru/beautiful-react-hooks/blob/519ebf1c7dd3fa01f25cd2e4258495280d415cd3/src/useWillUnmount.ts#L9-L25

By React doc for useEffect
```
After your component is removed from the DOM，
React will run your cleanup function.
```
So it should called `useUnmount`

**Comment by antonioru** [comment]
@little-buddy agree, feel free to open a PR

**Comment by little-buddy** [comment]
@antonioru awesome！
