### ISSUE TITLE
Type resolution for ESM modules is broken

### ISSUE THREAD

**Issue by phikes** [antonioru/beautiful-react-hooks#416]
**Describe the bug**

Using module imports with TS 5.1.6 leads to the following errors:

```
src/components/Token.tsx:6:24 - error TS7016: Could not find a declaration file for module 'beautiful-react-hooks/useUnmount'. '[...]/node_modules/beautiful-react-hooks/esm/useUnmount.js' implicitly has an 'any' type.
  There are types at '[...]/node_modules/beautiful-react-hooks/useUnmount.d.ts', but this result could not be resolved when respecting package.json "exports". The 'beautiful-react-hooks' library may need to update its package.json or typings.
```

**To Reproduce**

1. Create a ts file and import any hook as described in the README.md
2. Try compiling the file using `tsc`
3. Get the error above

**Expected behavior**

The import finds the right types

**Additional context**

This error happens because the package json specifies "./esm" as folder to import the module from but that folder does not contain the corresponding types. Refer to [Are the types wrong?](https://arethetypeswrong.github.io/?p=beautiful-react-hooks%405.0.0)

I am preparing a PR with a fix

**Comment by antonioru** [comment]
@phikes thank you for highlighting this, yes this is definitely something that needs to be fixed asap 
please feel free to contribute if you're willing to

**Comment by phikes** [comment]
No worries, my pleasure. I opened a PR and linked it to this issue: #417

**Comment by taro-ishihara** [comment]
Work around until it's merged.
```typescript
// @ts-ignore
import useLocalStorage from 'beautiful-react-hooks/useLocalStorage'
```

**Comment by antonioru** [comment]
@taro-ishihara @phikes 

this should have been solved guys, please let me know so I can close the issue

**Comment by phikes** [comment]
Works! Thank you!
