### ISSUE TITLE
Proposal to Update React Peer Dependency to Allow Installation of Later Versions

### ISSUE THREAD

**Issue by fakkio** [antonioru/beautiful-react-hooks#423]
**Is your feature request related to a problem? Please describe.**
The current peer dependency configuration in the `beautiful-react-hooks` package is preventing the installation of later versions of React, such as `18.3.1`, due to the exact version requirement of `18.2.0`. This limits users' ability to utilize the latest features and bug fixes in React.

**Describe the solution you'd like**
I propose updating the peer dependency of React in the `beautiful-react-hooks` package from `18.2.0` to `^18.2.0`. This would allow users to install later versions of React while maintaining compatibility with the package.

**Describe alternatives you've considered**
One alternative would be to force the React version to `18.3.1` in the `package.json` file of projects using `beautiful-react-hooks`. However, this approach may not be the best solution as it could lead to compatibility issues with other dependencies expecting a specific version of React. Additionally, it might hinder the flexibility of users in managing their dependencies.

**Additional context**
This change would enable users to benefit from the latest features and bug fixes in React without sacrificing compatibility with `beautiful-react-hooks`. It's essential to maintain flexibility in managing dependencies while ensuring users can leverage the advancements in the React ecosystem.

**Comment by antonioru** [comment]
Hey @fakkio , thanks a lot for opening this issue 

I believe you've found a bug in the way this package defines the peer dependencies, the correct approach is indeed the one you're suggesting: to change the peer dependency to react ^18.2.0.

Would you like to open a pull request? 
You've actually already solved the problem, it would be nice to have you among the contributors...

Let me know what you think, if you can't manage it, I'll update the package.json myself 

Speak soon and thanks a lot

**Comment by fakkio** [comment]
Hi @antonioru,

I'm more than happy to contribute to the project and open a pull request to implement this change.
I'll start working on the pull request right away.

Thank you!
